project_name: essh

builds:
  - main: .
    binary: essh
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

brews:
  - repository:
      owner: chenyhd
      name: homebrew-tap
    homepage: https://github.com/chenyhd/essh
    description: Encrypted SSH client — store server credentials, connect by name
    license: MIT

nfpms:
  - package_name: essh
    homepage: https://github.com/chenyhd/essh
    description: Encrypted SSH client — store server credentials, connect by name
    license: MIT
    formats:
      - deb
      - rpm

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
